---
title: "Week 3"
author: "Tad Dallas"
includes:
  in_header:
    - \usepackage{lmodern}
output:
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    highlight: tango
    theme: journal
---














## Environmental stochasticity

```{r}


logisticGrowth <- function(n, r, k){
  n+(n*r*(1-(n / k)))
}

logisticStochasticGrowth <- function(n, r, k){
  n <- sum(rbinom(n, 1, 0.9))
  n*exp(r*(1-(n / k)))
}

logisticDynamics <- function(n,r,k, steps=100, stochastic=FALSE){
  ret <- c()
  ret[1] <- n
  if(length(r) == 1){
    r <- rep(r, steps)
  }
  for(i in 1:(steps-1)){
    if(stochastic){
      ret[i+1] <- logisticStochasticGrowth(ret[i], r[i], k)
    }else{
      ret[i+1] <- logisticGrowth(ret[i], r[i], k)
    }
  }
  return(ret)
}

```


```{r}

stps <- 10

plot(1:stps,
 logisticDynamics(n=30, r=1, k=30, steps=stps),
  type='n', las=1, ylim=c(0,100),
  xlab='Time', 
  ylab='Population size', 
  col=1)


sapply(seq(5,30,by=1), function(x){
 lines(logisticDynamics(n=x, r=rep(c(0.5,1.5),5), k=30, steps=stps, stochastic=TRUE), col='firebrick')
})


sapply(seq(5,30,by=1), function(x){
 lines(logisticDynamics(n=x, r=rep(1,stps) + runif(stps,-0.5,0.5), 
  k=30, steps=stps), col='green')
})


```


















## Demographic stochasticity



```{r}

stps <- 10

plot(1:stps,
 logisticDynamics(n=30, r=1, k=30, steps=stps),
  type='n', las=1,ylim=c(0,100),
  xlab='Time', 
  ylab='Population size', 
  col=1)

sapply(rep(5,10), function(x){
 lines(logisticDynamics(n=x, r=1.5, k=30,
   steps=stps, stochastic=TRUE),
   col='dodgerblue')
})

sapply(rep(5,10), function(x){
 lines(logisticDynamics(n=x, r=1.5, k=30, steps=stps), col='firebrick')
})


```





```{r}

stps <- 100

plot(1:stps,
 logisticDynamics(n=30, r=1, k=500, steps=stps),
  type='n', las=1,ylim=c(0,1000),
  xlab='Time', 
  ylab='Population size', 
  col=1)


sapply(rep(5,10), function(x){
 lines(logisticDynamics(n=x, r=1.5, k=500,
   steps=stps, stochastic=TRUE),
   col='dodgerblue')
})

sapply(rep(900,10), function(x){
 lines(logisticDynamics(n=x, r=1.5, k=500,
   steps=stps, stochastic=TRUE),
   col='red')
})

sapply(rep(5,10), function(x){
 lines(logisticDynamics(n=x, r=1.5, k=30, steps=stps), col='firebrick')
})


```





























## Dispersal 


p = P(dispersal 1 unit)
p * p = probability that an individual disperses 2 units
p**3 = 3 units



```{r}

plot(dpois(1:10, lambda=1), type='l')
lines(1:10, 0.4**(1:10), lwd=2, col='dodgerblue')

```
















### Dispersal kernel shape

```{r}




```











### Variation in individual dispersal behavior

```{r}




```























n <- 10
b <- 0.5
d <- 0.5

N <- c()
N[1] <- n
for(i in 1:500){
  N[i+1] <- N[i]*rnorm(1,1,0.1) 
}


pdf('out.pdf')
plot(N, type='b', 
  col='dodgerblue',xlab='Time', ylab='Population size')
dev.off()
















