all: 
	+$(MAKE) -C 01_whatIsEcology
	+$(MAKE) -C 02_popDynamics
	+$(MAKE) -C 03_behavior
	+$(MAKE) -C 04_niche
	+$(MAKE) -C 05_communityComposition
	+$(MAKE) -C 06_landscapeStructure
	+$(MAKE) -C 07_trophicInteractions
	+$(MAKE) -C 08_diseaseEcology
	+$(MAKE) -C 09_plantPollinator
	+$(MAKE) -C 10_envChange
	+$(MAKE) -C 11_macroecology

		
clean:
	rm -fv */*.aux */*.log */*.toc */*.blg */*.bbl */*.synctex.gz
	rm -fv */*.nav */*.aux */*.snm 
	rm -fv */*.out */*.bcf */*blx.bib */*.run.xml
	rm -fv */*.fdb_latexmk */*.fls
