---
title: "Week 5"
author: "Tad Dallas"
includes:
  in_header:
    - \usepackage{lmodern}
output:
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    highlight: tango
    theme: journal
---



 




## The measurement of species diversity


Alpha, beta, gamma

```{r}








```





```{r}








```





```{r}








```










## Rarefaction


```{r}

# not really rarefaction, as I'm taking a subsample repeatedly, so the function is not inherently increasing. 

getRare <- function(x, len=200){
	rich <- c()
	for(i in 1:length(x)){
		rich[i] <- length(unique(sample(x, i, replace=TRUE)))
	}
	return(rich[1:len])
}

getPoint <- function(S=10, p, m){
	S-sum((1-p)**m)
}

species <- letters[1:10]
full <- sample(species, 1000, replace=TRUE)

rare1 <- getRare(full)
plot(y=rare1, x=1:length(rare1), 
	xlab='Individuals sampled', 
	ylab='Species richness', 
	pch=16, type='b', las=1)




full2 <- sample(species, 1000, 
	prob=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25),
	replace=TRUE)

rare2 <- getRare(full2)
plot(y=rare2, x=1:length(rare2), 
	xlab='Individuals sampled', 
	ylab='Species richness', 
	pch=16, type='b', las=1)

points(x=5, 
	getPoint(10, p=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25), m=5),
	pch=16, col='red', cex=2)
points(x=10, 
	getPoint(10, p=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25), m=10),
	pch=16, col='red', cex=2)
points(x=100, 
	getPoint(10, p=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25), m=100),
	pch=16, col='red', cex=2)

sapply(1:100, function(x){lines(getRare(full2))})	

```














```{r}

getRare <- function(x, len=200){
	rich <- c()
	x <- sample(x)
	for(i in 1:length(x)){
		rich[i] <- length(unique(x[1:i]))
	}
	return(rich[1:len])
}


species <- letters[1:10]
full <- sample(species, 1000, replace=TRUE)

rare1 <- getRare(full)
plot(y=rare1, x=1:length(rare1), 
	xlab='Individuals sampled', 
	ylab='Species richness', 
	pch=16, type='b', las=1)
sapply(1:100, function(x){lines(getRare(full))})




full2 <- sample(species, 1000, 
	prob=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25),
	replace=TRUE)

rare2 <- getRare(full2)
plot(y=rare2, x=1:length(rare2), 
	xlab='Individuals sampled', 
	ylab='Species richness', 
	pch=16, type='b', las=1)
sapply(1:100, function(x){lines(getRare(full2))})
points(x=5, 
	getPoint(10, p=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25), m=5),
	pch=16, col='red', cex=2)
points(x=10, 
	getPoint(10, p=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25), m=10),
	pch=16, col='red', cex=2)
points(x=100, 
	getPoint(10, p=c(0.025, 0.025, 0.05, 0.05, 0.1, 0.1, 0.1, 0.15, 0.15, 0.25), m=100),
	pch=16, col='red', cex=2)
	
```


















```{r}

getPoint <- function(S=13, p, m){
	S-sum((1-p)**m)
}

hwP <- c(0.14903129657228,
0.029806259314456,
0.596125186289121,
0.001490312965723,
0.049180327868853,
0.001490312965723,
0.002980625931446,
0.001490312965723,
0.07451564828614,
0.034277198211625,
0.014903129657228,
0.043219076005961,
0.001490312965723)


# 21 is the expected richness given the sample.

```








