---
title: "week 10: Environmental change"
author: "Tad Dallas"
date: ""
output:
  bookdown::pdf_document2: 
    latex_engine: xelatex
    number_sections: no
    toc: no
  html_document:
    df_print: paged
fontsize: 12pt
linestretch: 1.5
mainfont: Arial
urlcolor: blue
linkcolor: orange
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \rhead{Biol 4253}
  - \lhead{How does global environmental change influence ecology?}
  - \setlength{\headheight}{14.5pt}
---

```{r knitr_options, include=FALSE}
library(knitr)
opts_chunk$set(fig.align='center', cache = FALSE, warning = FALSE,
        message = FALSE, echo = FALSE, out.width = '95%')
options(digits = 3, width = 88)
if(!require(bookdown)) install.packages("bookdown")
```

\thispagestyle{fancy}

# Reading:

Camill, P. (2010) Global Change. Nature Education Knowledge 3(10):49 
[link to paper](https://www.nature.com/scitable/knowledge/library/global-change-an-overview-13255365)

Walther, G.R., Post, E., Convey, P., Menzel, A., Parmesan, C., Beebee, T.J., Fromentin, J.M., Hoegh-Guldberg, O. and Bairlein, F., 2002. Ecological responses to recent climate change. Nature, 416(6879), p.389. [link to paper](http://eebweb.arizona.edu/courses/Ecol206/Walther%20et%20al%20Nature%202002.pdf)







# How does global environmental change influence ecology?

Much of the material we've covered so far has focused on theory and/or the influence of a static environment. That is, the niche was defined in terms of abiotic tolerances, but when we projected the niche into geographic space, we considered the environmental niche axis to take on a single value over a reasonable timeline. However, ecological systems are changing, some more rapidly than others. Before we go any further into this topic, I will note that I am not attempting to pander to any political or social group. Much of what we talk about today touches on issues that are treated as partisan, which I really don't agree with, but we will not discuss the political or social implications. Instead we will focus on the science, and specifically on how land use and environmental change affects ecological systems across all scales of organization (individual -- ecosystem). 

So we can start by operationalizing what we mean by _land use change_ and _environmental change_. Here, we'll focus largely on human-induced changes to the landscape. 

_Land use change_ includes activities like logging, road/city development, and agriculture. That is, the physical land is changed from some (semi)-natural state to something pretty unnatural. This has direct effects on individual survival and subsequent population growth, as well as the potential to shift community structure when species differ in their sensitivity to disturbance. 

e.g., overhunting and fragmentation effects increasing extinction. 

_Environmental change_ refers to longer timescale changes to ecological systems, sometimes as a result of an indirect effect. This, in my definition, encompasses both _climate change_, and secondary effects of pollution (e.g., acid rain). Climate change refers to the longterm increase in mean annual temperature, and the associated phenomena relating to an increase in extreme weather events (e.g., floods).

e.g., Coral bleaching due to rising sea temperatures and ocean acidification (increased CO~2~ in the atmosphere is dissolving into oceans, making seawater more acidic, causing the coral skeletons to dissolve). 


_Greenhouse effect_ 

Let's talk about CO~2~ first. CO~2~ is made largely by the burning of fossil fuels, but has many environmental sources as well (forest fires, sloth breath, etc.). Solar radiation, particularly infrared radiation, becomes trapped by greenhouse gases, which keep infrared radiation closer to the earth (and infrared radiation is basically heat). This is called the "greenhouse effect". CO~2~ concentration has cycled over time (starting about 400k years ago, there have been 3-4 cycles), but the rapid rise in CO~2~ after the industrial revolution is now off the charts, indicating humans are affecting CO~2~ levels. This rise in CO~2~ is projected to change the mean temperature of the planet. This rise in temperature is associated with sea level rise. There's a lot of water in the ocean that is in the form of ice. Making it warmer makes that ice melt. Not good. 

**Impacts on humans** Extreme climatic events (e.g., floods, tornadoes) are expected to increase. Also, with sea level rise, many coastal cities may be at risk of flooding more often or being uninhabitable. 

Infectious diseases, on average, tend to be worse in higher temperatures. This is especially true of mosquito-vectored pathogens (e.g., malaria, dengue, chikingunya, etc.). 

The effect of climate change is also distributed non-randomly, where developing countries are at higher-risk due to the limited ability to respond to large environmental shifts, a potential dependency on natural resources, and simply where the country is located geographically. While the largest effects in terms of rates of change in temperature will be felt at the poles, the emergence of novel (never been observed) environmental conditions will be highest near the equator. This is especially true in terms of precipitation, which is expected to decrease in subtropical regions. 

**Impacts on phenology** Phenology is the timing of species seasonal life history events (e.g., spawning in fish, egg laying in birds, flowering in plants). Depending on what species use as a signal for such an event, climate change can have differing effects. Common changes are the earlier breeding of birds, earlier spawning of amphibians and fish, and earlier flowering times in plants. This is not necessarily a problem by itself, but consider the species that rely on seasonal plant or animal resources. For instance, insect pollinators of plants have to emerge at a time to best capitalize on the floral resource, but with phenological shifts, the flower could bloom without any insect pollinators at first. This is especially true if insects are responding to different cues for emergence. This leads to a _phenological mismatch_ between interacting species. 

**Impacts on species ranges** If species were staying completely within their niche limits, they might simply track their optimal environmental conditions through dispersal. Species could also adapt to a changing environment through behavioral changes. Lastly, species could die. This last option seems a bit silly, but occurs fairly often in slow-dispersing organisms, or organisms on mountains. 

e.g., elevational range limits on mountains. Plants can only go so high before they run out of suitable environments. 

**List of actionable items**: Waste less, eat less meat, drive less, fly less, buy less. 
